<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rateio.Domain\Rateio.Domain.csproj" />
    <ProjectReference Include="..\Rateio.Application\Rateio.Application.csproj" />
    <ProjectReference Include="..\Rateio.Infrastructure\Rateio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
