// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rateio.Infrastructure.Persistence;

#nullable disable

namespace Rateio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919230139_AdicionaCodigoConvite")]
    partial class AdicionaCodigoConvite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.CodigoConviteEntity", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.HasKey("Codigo");

                    b.HasIndex("GrupoId");

                    b.ToTable("codigos_convite", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uuid");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonoUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DonoUsuarioId");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipacaoDespesaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DespesaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Peso")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<long?>("ValorCentavos")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DespesaId");

                    b.ToTable("participacoes_despesa", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EhConvidado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("participantes", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.CodigoConviteEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", "Grupo")
                        .WithMany("Despesas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.UsuarioEntity", "Dono")
                        .WithMany()
                        .HasForeignKey("DonoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipacaoDespesaEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", "Despesa")
                        .WithMany("Participacoes")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", "Grupo")
                        .WithMany("Participantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.UsuarioEntity", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
