// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rateio.Infrastructure.Persistence;

#nullable disable

namespace Rateio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uuid");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("participantes", (string)null);
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.DespesaEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", "Grupo")
                        .WithMany("Despesas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.ParticipanteEntity", b =>
                {
                    b.HasOne("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", "Grupo")
                        .WithMany("Participantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Rateio.Infrastructure.Persistence.Entities.GrupoEntity", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
