<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tally.Domain\Tally.Domain.csproj" />
    <ProjectReference Include="..\Tally.Application\Tally.Application.csproj" />
    <ProjectReference Include="..\Tally.Infrastructure\Tally.Infrastructure.csproj" />
  </ItemGroup>

</Project>
