using Tally.Domain;

namespace Tally.Application.Groups;

/// <summary>
/// Persistence of synced groups. Concrete implementation (EF Core) in Tally.Infrastructure —
/// Application only knows this abstraction (SOLID: dependency inversion), same pattern already
/// established by <c>Tally.Application.Auth.IUserRepository</c>.
/// </summary>
public interface IGroupRepository
{
    /// <summary>
    /// Persists the group (with participants and expenses) for the first time and returns the
    /// group's id on the server — which is never the local Room id, but the new
    /// <see cref="Tally.Domain.Group.Id"/> generated by <see cref="Tally.Domain.Group.Create"/>,
    /// so the app knows which remote GroupId corresponds to the local group.
    /// </summary>
    Task<Guid> SyncAsync(GroupToSync group, CancellationToken cancellationToken = default);

    /// <summary>
    /// Group access summary, used to validate access before day-to-day operations like
    /// adding an expense — without loading participants/expenses, which the caller here doesn't
    /// need. <c>null</c> when the group doesn't exist; the caller decides whether that becomes a
    /// 404.
    /// </summary>
    Task<GroupAccess?> GetAccessAsync(Guid groupId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Minimal read for joining via invite: current name/category/participants, enough for
    /// <see cref="JoinGroupViaInviteUseCase"/> to reconstruct a <see cref="Group"/> and call
    /// <see cref="Group.AddParticipant"/> before persisting. <c>null</c> when the group doesn't
    /// exist.
    /// </summary>
    Task<GroupEntryInfo?> GetForEntryAsync(Guid groupId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Persists a single new <see cref="Participant"/> in a group that already exists —
    /// inserts directly via the FK (<c>GroupId</c>), without reloading the whole aggregate, same
    /// pattern as <c>Tally.Infrastructure.Expenses.ExpenseRepository.AddAsync</c>. The
    /// caller already validated the domain invariant via <see cref="Group.AddParticipant"/> before
    /// this call.
    /// </summary>
    Task AddParticipantAsync(Guid groupId, Participant participant, CancellationToken cancellationToken = default);
}
