<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Even.Domain\Even.Domain.csproj" />
    <ProjectReference Include="..\Even.Application\Even.Application.csproj" />
    <ProjectReference Include="..\Even.Infrastructure\Even.Infrastructure.csproj" />
  </ItemGroup>

</Project>
